apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-sa
  namespace: platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-a-sa
  namespace: tenant-a
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-b-sa
  namespace: tenant-b
