apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-reader-binding
  namespace: tenant-a # Cambiar a tenant-b para usar en tenant-b
subjects:
  - kind: ServiceAccount
    name: tenant-a-sa # Cambiar por tenant-b-sa en tenant-b
    namespace: tenant-a
roleRef:
  kind: Role
  name: tenant-reader
  apiGroup: rbac.authorization.k8s.io
